### ISSUE TITLE
Add #nostr tag to repo

### ISSUE THREAD

**Issue by melvincarvalho** [unclebob/more-speech#10]
Would it be possible to add the #nostr tag to this repo

It'll show up in this nice list here:

https://github.com/topics/nostr

**Comment by unclebob** [comment]
Sure. How do I do that?

**Comment by melvincarvalho** [comment]
https://github.com/unclebob/more-speech

![image](https://user-images.githubusercontent.com/65864/180603198-07972565-4596-4206-8514-0e5f54ff9c40.png)

----

This should give a popup

----

![image](https://user-images.githubusercontent.com/65864/180603219-d3b9250a-5e06-435c-ab69-452e7af30767.png)

**Comment by unclebob** [comment]
Got it.  Thanks!
