### ISSUE TITLE
Tests on Windows are failing

### ISSUE THREAD

**Issue by galuszkak** [unclebob/more-speech#11]
While preparing PR with Continous Integration on Github Actions, tests on Windows were actually failing.

More details here:
https://github.com/galuszkak/more-speech/runs/7589462808?check_suite_focus=true#step:7:105

```
Failures:

  1) Composing outgoing events composing metadata (kind:0) messages composes using the keys data structure
     Expected truthy but was: false
     /D:/a/more-speech/more-speech/spec/more_speech%5cnostr%5cevents_spec.clj:149

Finished in 2.32663 seconds
159 examples, 1 failures
```

**Comment by galuszkak** [comment]
Looks like when those tests were running the second time they actually passed...

**Comment by unclebob** [comment]
Windows works so far after merge.

**Comment by unclebob** [comment]
Have you seen any further failures on Windows?  None have occurred here.  Shall I close this issue?

**Comment by galuszkak** [comment]
@unclebob I've created PR #19 to close this. After merge of it we can close this.
