### ISSUE TITLE
NullPointerException when "Reply" clicked right after start

### ISSUE THREAD

**Issue by m1kal** [unclebob/more-speech#18]
When the app is started, it is possible to click "Reply" when no message is selected.

Then the console shows "Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException".

This has no impact on the app behavior, but I think `make-edit-window` should check if an article was selected before calling `format-reply`.

**Comment by unclebob** [comment]
Good idea. <grin>

**Comment by unclebob** [comment]
Done.
