### ISSUE TITLE
Clicking a http link inside an event blocks the UI thread until the browser is closed

### ISSUE THREAD

**Issue by TrentonZero** [unclebob/more-speech#21]
Given: open an event with an http link
Given: click the link
When: trying to use more-speech
Expected: can continue to use more-speech in a normal way
Actual: all rendering is frozen, cannot change tabs, resizing the window does not redraw the UI, etc.

Might also block the network calls, not sure. 

Edit: This is only true for browser windows opened by the app. If it just opens a new tab in an existing browser, nothing seems to block. 

Since it now seems potentially relevant, the browser I saw this on was Firefox 103.0.2 (64-bit) running on ArchLinux with the Gnome 42.4.

**Comment by unclebob** [comment]
Hmmm.  Yeah, it doesn't do that for me with Vivaldi.  There was a change made today to resolve issue #20 that created similar symptoms in windows.  Have you tried the latest commit?

**Comment by TrentonZero** [comment]
Just pulled and I still see it. 

I have some time later this week, I will see if I can dig deeper and either submit a PR or provide more information.

**Comment by unclebob** [comment]
That would be much appreciated.

**Comment by TrentonZero** [comment]
After looking deeper, I managed to trace this back to a problem on my own box. 

Everything ultimately falls through to xdg-open, which does not behave correctly in Gnome unless the XDG_CURRENT_DESKTOP env variable is set. Since I~~am a masocist~~ run ArchLinux with Gnome and with a hand-rolled .xinitrc, this was something I just missed.
