### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Aspie96** [unclebob/more-speech#25]
Hi!

Would you consider adding a license for this repo?

**Comment by galuszkak** [comment]
@Aspie96 license is defined in `project.clj` file 
See more here:
https://github.com/unclebob/more-speech/blob/c1726cc236bfeb8d58a68c7d7d517691c0cfd8ea/project.clj#L4-L5

**Comment by Aspie96** [comment]
Thank you a lot, I missed it!

**Comment by msgilligan** [comment]
I missed it, tool. And was about to open an issue and found this closed issue.

@unclebob If I made a PR adding an Eclipse license in a `LICENSE` file, would you accept it?
