### ISSUE TITLE
Consider participating in Hacktoberfest

### ISSUE THREAD

**Issue by galuszkak** [unclebob/more-speech#26]
@unclebob giving this under your consideration to have this one month where people gather together to help open source projects. I think more-speech fits very well with Hacktoberfest idea! 

Per rules available here (https://hacktoberfest.com/participation/), those are things to be considered if project like `more-speech` would like to participate in Hacktoberfest:

>  Prepare your project for contributions by following these best practices:
> * Add the “hacktoberfest” topic to your repository to opt-in to Hacktoberfest and indicate you’re looking for contributions.
> * Apply the “hacktoberfest” label to issues you want contributors to help with in your GitHub or GitLab project.
> * Add a CONTRIBUTING.md file with contribution guidelines to your repository.
> * Choose issues that have a well-defined scope and are self-contained.
> * Adopt a code of conduct to create a greater sense of inclusion and community for contributors.
> * Be ready to review pull/merge requests, accepting those that are valid by merging them, leaving an overall approving review, or by adding the “hacktoberfest-accepted” label.
>  * Reject any spammy requests you receive by labeling them as “spam,” and any other invalid contributions by closing them or labeling them as “invalid.”

**Comment by unclebob** [comment]
I'll consider it.
