### ISSUE TITLE
Public relay name change

### ISSUE THREAD

**Issue by bleetube** [unclebob/more-speech#37]
nostr.bitcoiner.social -> offchain.pub

note1zpgy9f8tlwdwhhwtzy50vpl72qkunzhmy57p4f5xaf8h57pfvwpschwe74

> Before I deployed the new pay-to-relay server, I ran a public relay under a "nostr" subdomain. I've since renamed my public relay to wss://offchain.pub. Much cooler name. Better represents how nostr isn't something this domain handles on the side, it's the primary purpose. Raison d'etre.
> 
> Both offchain.pub and the "nostr" subdomain will work concurrently for awhile, pointing to the same public relay server. But I'll eventually deprecate the "nostr" subdomain and redirect requests to the new offchain.pub name.

I saw references to the old name in `nostr-messages` and was going to open a PR but I'm a little wary of assuming too much about what this file is for. This is probably how I'd fix it:

```bash
sed -i 's/nostr.bitcoiner.social/offchain.pub/g' nostr-messages
```

**Comment by unclebob** [comment]
Thanks.
