### ISSUE TITLE
Formatters specs are failing on different environment.

### ISSUE THREAD

**Issue by coola** [unclebob/more-speech#6]
![image](https://user-images.githubusercontent.com/83182/171160450-405b18ad-6078-4275-90e7-2e3ddf3b5f6a.png)

This is failing on my environment. 

I have Windows 11 on Polish/Poland locale. 

I tried to add ROOT locale, but it does not work: 
![image](https://user-images.githubusercontent.com/83182/171161066-c4d71a77-9490-456f-86db-b5ce3d794804.png)

**Comment by unclebob** [comment]
That looks like a time-zone issue.  My tests assume the time zone of my machine (CDT).  I'll have to modify the tests to be time-zone independent.

**Comment by unclebob** [comment]
Fixed by sathwikmatsa
